### PR TITLE
Chinmay

### PR DESCRIPTION
**Pull request by chinmayms**

### CODE REVIEW

**Comment by gcallah** [comment]
Thanks Chinmay! What are the xml files?

**Comment by gcallah** [comment]
And the iml files?

**Comment by chinmayms** [comment]
Sorry about those,The quiz files were untracked so I added all files. It seems some internal windows files got added too. I don't think they are relevant.

**Comment by gcallah** [comment]
OK, can you remove them and re-do the request? Because we don't want to pile up irrelevant material in the repo.
But thanks again for your speedy work!

**Comment by gcallah** [comment]
"git rm filename" will get rid of them (where "filename" is the real name of the file!)

**Pull request closed without merging**
